name: Run CI checks

on: [pull_request]

jobs:
  test-qm-app:
    runs-on: ubuntu-latest
    name: Test Store
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: npm run nx test qm-app2
  test-ui: 
    runs-on: ubuntu-latest 
    name: Test UI
    steps: 
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: npm run nx test ui
